### ISSUE TITLE
Flavors not created with idempotency

### ISSUE THREAD

**Issue by oneswig** [stackhpc/ansible-role-os-flavors#8]
It appears that when flavors already exist, the role will replace them with a new flavor with the same attributes but different UUID.

This is likely to cause big problems, eg for Heat stack updates

This was found with ansible (both 2.10.5 and 2.9.17), openstacksdk 0.53.0 and Ussuri.

**Comment by cityofships** [comment]
This hasn't been the case in SMS Lab with ansible 2.9.17 and openstacksdk 0.50.0. The role is executed there on a regular basis via CI.

**Comment by oneswig** [comment]
Reported elsewhere recently, it appears flavors that have additional properties are recreated, and without the additional properties defined.

Try to reproduce with flavors that have properties (https://docs.openstack.org/nova/wallaby/user/flavors.html#extra-specs)

**Comment by MoteHue** [comment]
I've done some testing, and have been unable to recreate this issue.

I used ansible version 5.10.0, with various versions of os-openstacksdk and os-flavors to see if there was an issue between versions:
os-openstacksdk versions 1.0.0, 1.0.1, 1.2.0, 1.3.0
os-flavors versions 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0

Tested with the following playbook, in an aufn environment: 
```---
- name: Ensure nova flavors are registered
  hosts: localhost
  roles:
    - role: stackhpc.os-flavors
      os_flavors_venv: "~/os-flavors-venv"
      os_flavors_auth_type: "{{ openstack_auth_type }}"
      os_flavors_auth: "{{ openstack_auth }}"
      os_flavors:
        - name: flavor-1
          ram: 1024
          disk: 1024
          vcpus: 1
          extra_specs:
            hw:cpu_policy: "dedicated"
            hw:numa_nodes: "1"
            quota:memory_limit: 512

**Comment by MoteHue** [comment]
I've been able to recreate this issue. It occurs on ansible versions below (and including) 4.1.0.
(for completeness, I tested ansible versions 2.9.17, 2.10.5, 2.10.7, 3.0.0, 3.4.0, 4.0.0, 4.1.0, 4.2.0, 4.5.0, 4.10.0, 5.10.0)

The version of openstacksdk does not seem to change the behaviour.

The flavors are created with new UUIDs regardless of if extra specs are requested or not.
Where extra specs are defined, the flavor is indeed recreated without them, but as the issue occurs even without them I doubt they are the cause.

I will investigate further to find how this issue was fixed in ansible version 4.2.0

**Comment by MoteHue** [comment]
It appears the bug was part of the `os_nova_flavor` module. It was fixed [here](https://opendev.org/openstack/ansible-collections-openstack/commit/21b70f6b9b04b2684d155abd302943f5c8d3ed45).

Also worth noting: [`os_` prefixed module names are deprecated](https://docs.ansible.com/ansible/latest/collections/openstack/cloud/os_nova_flavor_module.html#id1) so the os-flavors role should probably be updated to instead use [`openstack.cloud.compute_flavor`](https://docs.ansible.com/ansible/latest/collections/openstack/cloud/compute_flavor_module.html#ansible-collections-openstack-cloud-compute-flavor-module).

**Comment by bbezak** [comment]
This can be decoupled from ansible version with installing https://galaxy.ansible.com/openstack/cloud - os_nova_flavor will still work then, as stable releases still does the redirection - https://opendev.org/openstack/ansible-collections-openstack/src/branch/stable/1.0.0/plugins/modules/os_nova_flavor.py. However this behaviour won't work in future 2.0 releases.

**Comment by oneswig** [comment]
From testing I think this issue is resolved by use of latest Ansible OpenStack cloud modules.
